# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre/s de la persona')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido/s de la persona')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenimo')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('contra', models.CharField(blank=True, max_length=50, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Rol', verbose_name='Rol del usuario')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Usuario', verbose_name='Usuario login'),
        ),
    ]
