# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
