# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190326_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='acrivo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
